tracking_recovery_matchers:
    point_matchers:
#        iterative_closest_point:
#        iterative_closest_point_non_linear:
        iterative_closest_point_with_normals:
#        iterative_closest_point_generalized:
            convergence_time_limit_seconds: 0.450
            max_correspondence_distance: 5.0
            transformation_epsilon: 0.001
            euclidean_fitness_epsilon: 0.001
            max_number_of_registration_iterations: 250
            max_number_of_ransac_iterations: 150
            ransac_outlier_rejection_threshold: 0.07
            match_only_keypoints: false
            display_cloud_aligment: false
            maximum_number_of_displayed_correspondences: 0
            use_reciprocal_correspondences: false


transformation_validators_tracking_recovery:
    euclidean_transformation_validator:
        max_transformation_angle: 0.9
        max_transformation_distance: 2.0
        max_new_pose_diff_angle: 1.57
        max_new_pose_diff_distance: 2.5
        max_root_mean_square_error: 0.07
        max_outliers_percentage: 0.4
