tracking_matchers:
    ignore_height_corrections: false
    point_matchers:
#        iterative_closest_point:
        iterative_closest_point_2d:
#        iterative_closest_point_non_linear:
#        iterative_closest_point_generalized:
#        normal_distributions_transform_2d:
            convergence_time_limit_seconds: 0.09
            max_correspondence_distance: 0.5
            transformation_epsilon: 0.000001
            euclidean_fitness_epsilon: 0.000001
            max_number_of_registration_iterations: 150
            max_number_of_ransac_iterations: 20
            ransac_outlier_rejection_threshold: 0.035
            match_only_keypoints: false
            display_cloud_aligment: false
            maximum_number_of_displayed_correspondences: 0
            # gicp
            rotation_epsilon: 0.002
            correspondence_randomness: 50
            maximum_optimizer_iterations: 100
            use_reciprocal_correspondences: false
            # ndt_2d
            grid_center_x: 10.0
            grid_center_y: 5.0
            grid_step_x: 0.05
            grid_step_y: 0.05
            grid_extent_x: 20.0
            grid_extent_y: 20.0
            grid_optimization_step_size_x: 0.05
            grid_optimization_step_size_y: 0.05
            grid_optimization_step_size_theta: 0.025


outlier_detectors:
    euclidean_outlier_detector:
        max_inliers_distance: 0.07
        aligned_pointcloud_outliers_publish_topic: 'aligned_pointcloud_outliers'
        aligned_pointcloud_inliers_publish_topic: 'aligned_pointcloud_inliers'


#cloud_analyzers:
#    compute_inliers_angular_distribution: true
#    compute_outliers_angular_distribution: true
#    angular_distribution_analyzer:
#        number_of_angular_bins: 180


transformation_validators:
    euclidean_transformation_validator:
        max_transformation_angle: 0.7
        max_transformation_distance: 0.5
        max_new_pose_diff_angle: 1.1
        max_new_pose_diff_distance: 1.0
        max_root_mean_square_error: 0.04
        max_outliers_percentage: 0.6
        min_inliers_angular_distribution: 0.125
        max_outliers_angular_distribution: 0.875
