#message_management:
#    maximum_number_points_ambient_pointcloud_circular_buffer: 750

normal_estimators:
    reference_pointcloud:
        display_normals: false
        display_occupancy_grid_pointcloud: false
        use_filtered_cloud_as_normal_estimation_surface: false
        flip_normals_using_occupancy_grid_analysis: true
        occupancy_grid_analysis_radius_resolution_percentage: 4.0
#        normal_estimation_omp:
#            search_k: 0
#            search_radius: 0.35
    ambient_pointcloud:
        compute_normals_when_tracking_pose: false
        compute_normals_when_recovering_pose_tracking: false
        compute_normals_when_estimating_initial_pose: true
        use_filtered_cloud_as_normal_estimation_surface: false
        display_normals: false
        normal_estimation_omp:
            search_k: 0
            search_radius: 0.35



tracking_matchers:
    ignore_height_corrections: false
    point_matchers:
        iterative_closest_point:
#        iterative_closest_point_non_linear:
#        iterative_closest_point_with_normals:
#        iterative_closest_point_generalized:
            convergence_time_limit_seconds: 0.250
            max_correspondence_distance: 2.0
            transformation_epsilon: 0.0001
            euclidean_fitness_epsilon: 0.0001
            max_number_of_registration_iterations: 150
            max_number_of_ransac_iterations: 50
            ransac_outlier_rejection_threshold: 0.05
            match_only_keypoints: false
            display_cloud_aligment: false
            maximum_number_of_displayed_correspondences: 0
            rotation_epsilon: 0.002
            correspondence_randomness: 50
            maximum_optimizer_iterations: 100
            use_reciprocal_correspondences: false


outlier_detectors:
    euclidean_outlier_detector:
        max_inliers_distance: 0.06
        aligned_pointcloud_outliers_publish_topic: 'aligned_pointcloud_outliers'
        aligned_pointcloud_inliers_publish_topic: 'aligned_pointcloud_inliers'


transformation_validators:
    euclidean_transformation_validator:
        max_transformation_angle: 0.3
        max_transformation_distance: 0.05
        max_new_pose_diff_angle: 1.0
        max_new_pose_diff_distance: 0.5
        max_root_mean_square_error: 0.05
        max_outliers_percentage: 0.07


transformation_validators_tracking_recovery:
    euclidean_transformation_validator:
        max_root_mean_square_error: 0.05
        max_outliers_percentage: 0.1
